#!/usr/bin/env bash
#
# Install pyplater (to local $HOME/bin).
#

install_dir="$HOME/bin"
from_dir="${PWD}"

templates_dir="$HOME/.local/share/pyplates"

ln -s "$from_dir/pyplater.py" "$install_dir"
cp -r "pyplates/" "$templates_dir"
